name: 'Docker Publish'
description: 'An action to build a Docker image and publish it to a registry'
inputs:
  context:
    description: 'Dockerfile path'
    required: true
  tags:
    description: 'Publish tag'
    required: true
  file:
    description: 'Dockerfile path'
    required: false
runs:
  using: "composite"
  steps:
    - name: Build and publish
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        file: ${{ inputs.file }}
        platforms: linux/amd64,linux/arm64/v8
        tags: ${{ inputs.tags }}
